import type { Metadata } from "next";
import { Inter, Kanit, Sarabun } from "next/font/google";
import "../globals.css";
import ResponsiveDrawer from "./components/ResponsiveDrawer";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard Page",
  description: "Generated by create next app",
};

export default async function DashboaedRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ResponsiveDrawer session={session}>{children}</ResponsiveDrawer>
      </body>
    </html>
  );
}
